const tideCard=document.querySelector('.tide');
fetch('tide-data.json',{cache:'no-store'}).then(r=>r.json()).then(data=>{if(!data.points?.length)return;const fmt=t=>String(t).match(/(\d{2}):(\d{2})/)?.slice(1).join(':')||t;[...tideCard.querySelectorAll('.timeline span')].forEach((el,i)=>{if(data.points[i])el.textContent=fmt(data.points[i].time)});const n=data.points.find(p=>new Date(p.time)>new Date());if(n){const ms=new Date(n.time)-new Date(),e=tideCard.querySelector('.tide-main strong');if(e)e.textContent=new Date(Math.max(0,ms)).toISOString().slice(11,19)}}).catch(()=>{});
if(tideCard){const style=document.createElement('style');style.textContent='.tide-alert{display:flex;gap:10px;align-items:center;padding:11px 13px;border-radius:12px;margin:15px 0 12px;font-size:13px}.tide-alert b,.tide-alert small{display:block}.tide-alert small{margin-top:3px;opacity:.8}.tide-alert.safe{background:#eaf8f1;color:#08784c}.tide-alert.warn{background:#fff6dc;color:#936400}.tide-alert.danger{background:#fff0f2;color:#bd2442}.alert-dot{width:9px;height:9px;border-radius:50%;background:currentColor;flex:0 0 auto}.tide-events{display:flex;gap:8px;flex-wrap:wrap;margin:16px 0 4px;padding:10px 12px;border-left:3px solid #f0a72d;background:#fff8e9;color:#7a5613;font-size:12px}.tide-events small{width:100%;opacity:.8}.tide-live-graph{width:100%;height:100px;margin-top:16px;background:#f7fafb;border-radius:6px}.tide-live-graph path{fill:none;stroke:#559ed0;stroke-width:3}.tide-live-graph circle{fill:#ed654f;stroke:white;stroke-width:3}';document.head.appendChild(style);const timeline=tideCard.querySelector('.timeline');timeline.insertAdjacentHTML('beforebegin','<div class="tide-alert warn"><span class="alert-dot"></span><div><b>?꾩옱 議곗꽍 ?곹깭: 二쇱쓽</b><small>?꾩옱 ?쒓컖??留욎떠 議곗꽍 怨≪꽑怨??꾪뿕 ?쒓컙?瑜?怨꾩궛?⑸땲??</small></div></div>');timeline.insertAdjacentHTML('afterend','<svg class="tide-live-graph" viewBox="0 0 600 100" preserveAspectRatio="none" aria-label="?꾩옱 ?쒓컖 湲곗? 議곗꽍 洹몃옒??><path id="tide-live-path"></path><circle id="tide-live-dot" r="6"></circle></svg><div class="tide-events"><span>?꾪뿕 ?쒓컙?</span><b>留뚯“ ?꾪썑 짹40遺?/b><small id="tide-live-copy">?꾩옱 ?쒓컖??怨꾩궛 以묒엯?덈떎.</small></div>');const low1=6*60+12,high=16*60+50,low2=23*60+4;const nowMinutes=()=>{const n=new Date();return n.getHours()*60+n.getMinutes()+n.getSeconds()/60};const tideValue=m=>{let a,b,v1,v2;if(m<low1){a=low1-12*60;b=low1;v1=180;v2=70}else if(m<high){a=low1;b=high;v1=70;v2=180}else{a=high;b=low2;v1=180;v2=65}const t=Math.max(0,Math.min(1,(m-a)/(b-a)));return v1+(v2-v1)*(0.5-0.5*Math.cos(Math.PI*t))};const renderTide=()=>{const m=nowMinutes(),start=m-360,pts=[];for(let i=0;i<=600;i+=10){const v=tideValue(start+i*1.44);pts.push(`${i},${94-(v-60)*.32}`)}document.getElementById('tide-live-path').setAttribute('d','M'+pts.join(' L'));const x=360,y=94-(tideValue(m)-60)*.32;const dot=document.getElementById('tide-live-dot');dot.setAttribute('cx',x);dot.setAttribute('cy',y);const risky=Math.abs(m-high)<=40||Math.abs(m-low2)<=40;const alert=tideCard.querySelector('.tide-alert');alert.className='tide-alert '+(risky?'danger':'safe');alert.querySelector('b').textContent='?꾩옱 議곗꽍 ?곹깭: '+(risky?'?꾪뿕':'?뺤긽');alert.querySelector('small').textContent=`?꾩옱 ${String(Math.floor(m/60)%24).padStart(2,'0')}:${String(Math.floor(m%60)).padStart(2,'0')} 쨌 異붿젙 議곗쐞 ${Math.round(tideValue(m))}cm`;document.getElementById('tide-live-copy').textContent=risky?'留뚯“쨌媛꾩“ ?꾪썑 ?꾪뿕 援ш컙?낅땲?? ?댁븞 ?쒕룞??以묒??섏꽭??':'?ㅼ쓬 ?꾪뿕 援ш컙? 留뚯“쨌媛꾩“ ?쒓컖 ?꾪썑 40遺꾩엯?덈떎.'};renderTide();setInterval(renderTide,1000)}
const toast=document.getElementById('toast');
const zoneMap=document.querySelector('.zone-map');
if(zoneMap)zoneMap.style.height='260px';
if(zoneMap){const mapStyle=document.createElement('style');mapStyle.textContent='#map{height:100%;width:100%;z-index:1}';document.head.appendChild(mapStyle)}
if(zoneMap){zoneMap.innerHTML='<div id="map" aria-label="遺???욌컮???꾪뿕 吏??吏??></div>';const css=document.createElement('link');css.rel='stylesheet';css.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';document.head.appendChild(css);const js=document.createElement('script');js.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';js.onload=()=>{const map=L.map('map',{zoomControl:true}).setView([35.1532,129.1186],13);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'짤 OpenStreetMap contributors'}).addTo(map);const danger=L.circleMarker([35.1796,129.1996],{radius:9,color:'#ee6a52',fillColor:'#ee6a52',fillOpacity:.9}).addTo(map).bindPopup('<b>?≪젙 諛⑺뙆??/b><br>?덉슱???뚮룄 쨌 ?묎렐 二쇱쓽');const caution=L.circleMarker([35.1747,129.2075],{radius:8,color:'#edae45',fillColor:'#edae45',fillOpacity:.9}).addTo(map).bindPopup('<b>援щ뜒??媛?컮??/b><br>誘몃걚??二쇱쓽');L.circle([35.18,129.2],{radius:900,color:'#ee6a52',fillColor:'#ee6a52',fillOpacity:.08,weight:1}).addTo(map);const fishingBanZones=[['화명생태공원',35.2075,129.0010],['대저생태공원',35.1870,128.9580],['삼락생태공원',35.1770,128.9780],['맥도생태공원',35.1510,128.9410],['을숙도생태공원',35.1050,128.9460]];fishingBanZones.forEach(([name,lat,lon])=>{L.circleMarker([lat,lon],{radius:8,color:'#ee6a52',fillColor:'#ee6a52',fillOpacity:.9}).addTo(map).bindPopup('<b>'+name+'</b><br>낚시·취사·야영 금지');L.circle([lat,lon],{radius:500,color:'#ee6a52',fillColor:'#ee6a52',fillOpacity:.08,weight:1}).addTo(map)});setTimeout(()=>map.invalidateSize(),200)};document.head.appendChild(js)}
function show(m){if(!toast)return;toast.innerHTML=m;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2800)}
document.getElementById('sos')?.addEventListener('click',()=>{if(confirm('119??湲닿툒 ?좉퀬 ?꾪솕瑜??곌껐?좉퉴??'))window.location.href='tel:119'});
document.getElementById('locate')?.addEventListener('click',()=>{if(!navigator.geolocation)return show('??釉뚮씪?곗????꾩튂 ?뺣낫瑜?吏?먰븯吏 ?딆뒿?덈떎.');if(location.protocol==='file:')return show('蹂댁븞???뚯씪?먯꽌 ?꾩튂瑜??ъ슜?????놁뒿?덈떎. http://localhost濡??ㅽ뻾??二쇱꽭??');show('媛源뚯슫 ?댁닔?뺤옣??李얜뒗 以묒엯?덈떎...');navigator.geolocation.getCurrentPosition(async p=>{const lat=p.coords.latitude,lon=p.coords.longitude;try{const q=`[out:json];(nwr["leisure"="beach"](around:10000,${lat},${lon});nwr["natural"="beach"](around:10000,${lat},${lon}););out center tags;`;const r=await fetch('https://overpass-api.de/api/interpreter?data='+encodeURIComponent(q));const d=await r.json();const dist=(a,b)=>{const R=6371000,x=(b.lat-a.lat)*Math.PI/180,y=(b.lon-a.lon)*Math.PI/180;return 2*R*Math.asin(Math.sqrt(Math.sin(x/2)**2+Math.cos(a.lat*Math.PI/180)*Math.cos(b.lat*Math.PI/180)*Math.sin(y/2)**2))};const places=d.elements.map(x=>({name:x.tags?.name||x.tags?.['name:ko'],lat:x.lat??x.center?.lat,lon:x.lon??x.center?.lon})).filter(x=>x.name&&x.lat&&x.lon).map(x=>({...x,meters:dist({lat,lon},x)})).sort((a,b)=>a.meters-b.meters);if(!places.length)throw Error('none');const b=places[0],map=`https://www.google.com/maps/search/?api=1&query=${b.lat},${b.lon}`;show(`媛??媛源뚯슫 ?댁닔?뺤옣: <b>${b.name}</b> (${Math.round(b.meters)}m) 쨌 <a href="${map}" target="_blank" rel="noopener">Google Maps ?닿린</a>`)}catch(e){show('二쇰? ?댁닔?뺤옣??李얠? 紐삵뻽?듬땲??')}},e=>show(e.code===1?'?꾩튂 沅뚰븳??嫄곕??섏뿀?듬땲?? 二쇱냼李쎌뿉???덉슜??二쇱꽭??':e.code===2?'湲곌린???꾩튂 ?뺣낫瑜??뺤씤?????놁뒿?덈떎.':'?꾩튂 ?뺤씤 ?쒓컙??珥덇낵?섏뿀?듬땲??'),{enableHighAccuracy:true,timeout:10000,maximumAge:0})});
document.getElementById('isolation')?.addEventListener('click',()=>show('怨좊┰ ?꾪뿕 ?뚮┝???뺤씤?덉뒿?덈떎.'));
const species=document.querySelector('.species');
if(species){species.innerHTML=`<div class="panel-head"><div><span class="tag violet">FISH RISK CHECK</span><h2>臾쇨퀬湲??꾪뿕???먮퀎</h2></div><span class="count">?ㅻ챸 湲곕컲</span></div><p class="species-guide">?ъ쭊 ?놁씠 臾쇨퀬湲곗쓽 ?앷??덉? ?됰룞???곸뼱 二쇱꽭??</p><textarea id="fish-description" class="fish-description" placeholder="?? 紐몄씠 湲멸퀬 ?諛깆깋?대ŉ ?낆씠 ?ш퀬 ?대묠???좎뭅濡?뒿?덈떎."></textarea><div class="fish-actions"><button class="secondary" id="clear-fish">吏?곌린</button><button class="primary" id="check-fish">?꾪뿕???먮퀎</button></div><div class="safe"><span>??/span> 李멸퀬???덈궡?낅땲?? ??꽑 臾쇨퀬湲곕뒗 留뚯?吏 留덉꽭??</div><div id="fish-result" class="fish-result" hidden></div>`;const input=document.getElementById('fish-description'),result=document.getElementById('fish-result');document.getElementById('clear-fish').onclick=()=>{input.value='';result.hidden=true};document.getElementById('check-fish').onclick=()=>{const t=input.value.trim();if(!t)return show('臾쇨퀬湲??뱀쭠??癒쇱? ?낅젰??二쇱꽭??');const h=['??,'移?,'怨듦꺽','臾쇱뿀','?섏?','?꾧린','蹂듭뼱','?곸뼱','?댄뙆由?].filter(k=>t.includes(k)),c=['媛??,'?대묠','?좎뭅','????,'?듭꽱','肉?,'??꽑'].filter(k=>t.includes(k));const level=h.length?'?믪쓬':c.length?'二쇱쓽':'??쓬',cls=level==='?믪쓬'?'high':level==='二쇱쓽'?'medium':'low';result.hidden=false;result.className=`fish-result ${cls}`;result.innerHTML=`<b>?먯젙 寃곌낵: ${level}</b><p>${level==='?믪쓬'?'?묒큺?섏? 留먭퀬 利됱떆 嫄곕━瑜??뺣낫?섏꽭?? ?꾩슂?섎㈃ 119???곕씫?섏꽭??':level==='二쇱쓽'?'?먯쓣 ?吏 留먭퀬 愿李곕쭔 ?섏꽭??':'?쒕졆???꾪뿕 ?좏샇媛 ?곸?留??쇱깮 臾쇨퀬湲곕뒗 留뚯?吏 留덉꽭??'}</p><small>?먮퀎 洹쇨굅: ${[...h,...c].join(', ')||'?낅젰???꾪뿕 ?뱀쭠 ?놁쓬'}</small>`}}

document.title='낚시 메이트 · 해양 안전 관제';
const brandName=document.querySelector('.brand b'); if(brandName) brandName.textContent='낚시 메이트';
const brandSub=document.querySelector('.brand small'); if(brandSub) brandSub.textContent='FISHING MATE';

const descriptionSpeciesCard=document.querySelector('.species');
if (descriptionSpeciesCard) {
  descriptionSpeciesCard.innerHTML = `
    <div class="panel-head"><div><span class="tag violet">SPECIES CHECK</span><h2>묘사로 어종 확인</h2></div><span class="count">사용자 입력 기반</span></div>
    <p class="species-guide">사진 없이 물고기의 특징을 입력하면 예상 어종과 위험 정보를 안내합니다.</p>
    <textarea id="fish-description" class="fish-description" placeholder="예: 은빛 몸통, 검은 줄무늬, 약 25cm, 방파제에서 잡았어요"></textarea>
    <div class="fish-actions"><button class="secondary" id="clear-fish">지우기</button><button class="primary" id="check-fish">어종 확인</button></div>
    <div class="safe"><span>✓</span> 결과는 참고용이며 확실하지 않으면 만지지 마세요.</div>
    <div id="fish-result" class="fish-result" hidden></div>`;
  const input=document.getElementById('fish-description'), result=document.getElementById('fish-result');
  document.getElementById('clear-fish').onclick=()=>{input.value='';result.hidden=true;};
  document.getElementById('check-fish').onclick=()=>{
    const text=input.value.trim();
    if(!text){show('물고기의 특징을 먼저 입력해 주세요.');return;}
    const dangerous=['복어','쏨뱅이','미역치','쑤기미','가시','독','날카로운 이빨'].some(k=>text.includes(k));
    const clues=text.includes('줄무늬')?'돌돔·벤자리 등 줄무늬 어종':text.includes('은빛')?'전갱이·고등어 등 회유성 어종':text.includes('납작')?'가자미·광어 등 납작한 어종':'특징이 비슷한 연안 어종';
    result.hidden=false; result.className='fish-result '+(dangerous?'high':'low');
    result.innerHTML=`<b>예상 어종군: ${clues}</b><p>${dangerous?'가시나 독성이 있을 수 있으니 만지지 말고 사진과 함께 전문가에게 확인받으세요.':'추가로 몸 길이, 지느러미 색, 발견 장소를 입력하면 더 정확해집니다.'}</p><small>입력한 묘사 기반 참고 결과</small>`;
  };
}
