const tideCard=document.querySelector('.tide');
if(tideCard){const style=document.createElement('style');style.textContent='.tide-alert{display:flex;gap:10px;align-items:center;padding:11px 13px;border-radius:12px;margin:15px 0 12px;font-size:13px}.tide-alert b,.tide-alert small{display:block}.tide-alert small{margin-top:3px;opacity:.8}.tide-alert.safe{background:#eaf8f1;color:#08784c}.tide-alert.warn{background:#fff6dc;color:#936400}.tide-alert.danger{background:#fff0f2;color:#bd2442}.alert-dot{width:9px;height:9px;border-radius:50%;background:currentColor;flex:0 0 auto}.tide-events{display:flex;gap:8px;flex-wrap:wrap;margin:16px 0 4px;padding:10px 12px;border-left:3px solid #f0a72d;background:#fff8e9;color:#7a5613;font-size:12px}.tide-events small{width:100%;opacity:.8}';document.head.appendChild(style);const timeline=tideCard.querySelector('.timeline');timeline.insertAdjacentHTML('beforebegin','<div class="tide-alert warn"><span class="alert-dot"></span><div><b>현재 조석 상태: 주의</b><small>16:10–17:30 위험 시간대가 감지되었습니다. 해안 활동에 주의하세요.</small></div></div>');timeline.insertAdjacentHTML('afterend','<div class="tide-events"><span>위험 시간대</span><b>16:10–17:30</b><small>만조 전후 · 조위 1.8m</small></div>')}
const toast=document.getElementById('toast');
function show(m){if(!toast)return;toast.innerHTML=m;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2800)}
document.getElementById('sos')?.addEventListener('click',()=>{if(confirm('119에 긴급 신고 전화를 연결할까요?'))window.location.href='tel:119'});
document.getElementById('locate')?.addEventListener('click',()=>{if(!navigator.geolocation)return show('이 브라우저는 위치 정보를 지원하지 않습니다.');if(location.protocol==='file:')return show('보안상 파일에서 위치를 사용할 수 없습니다. http://localhost로 실행해 주세요.');show('가까운 해수욕장을 찾는 중입니다...');navigator.geolocation.getCurrentPosition(async p=>{const lat=p.coords.latitude,lon=p.coords.longitude;try{const q=`[out:json];(nwr["leisure"="beach"](around:10000,${lat},${lon});nwr["natural"="beach"](around:10000,${lat},${lon}););out center tags;`;const r=await fetch('https://overpass-api.de/api/interpreter?data='+encodeURIComponent(q));const d=await r.json();const dist=(a,b)=>{const R=6371000,x=(b.lat-a.lat)*Math.PI/180,y=(b.lon-a.lon)*Math.PI/180;return 2*R*Math.asin(Math.sqrt(Math.sin(x/2)**2+Math.cos(a.lat*Math.PI/180)*Math.cos(b.lat*Math.PI/180)*Math.sin(y/2)**2))};const places=d.elements.map(x=>({name:x.tags?.name||x.tags?.['name:ko'],lat:x.lat??x.center?.lat,lon:x.lon??x.center?.lon})).filter(x=>x.name&&x.lat&&x.lon).map(x=>({...x,meters:dist({lat,lon},x)})).sort((a,b)=>a.meters-b.meters);if(!places.length)throw Error('none');const b=places[0],map=`https://www.google.com/maps/search/?api=1&query=${b.lat},${b.lon}`;show(`가장 가까운 해수욕장: <b>${b.name}</b> (${Math.round(b.meters)}m) · <a href="${map}" target="_blank" rel="noopener">Google Maps 열기</a>`)}catch(e){show('주변 해수욕장을 찾지 못했습니다.')}},e=>show(e.code===1?'위치 권한이 거부되었습니다. 주소창에서 허용해 주세요.':e.code===2?'기기의 위치 정보를 확인할 수 없습니다.':'위치 확인 시간이 초과되었습니다.'),{enableHighAccuracy:true,timeout:10000,maximumAge:0})});
document.getElementById('isolation')?.addEventListener('click',()=>show('고립 위험 알림을 확인했습니다.'));
const species=document.querySelector('.species');
if(species){species.innerHTML=`<div class="panel-head"><div><span class="tag violet">FISH RISK CHECK</span><h2>물고기 위험도 판별</h2></div><span class="count">설명 기반</span></div><p class="species-guide">사진 없이 물고기의 생김새와 행동을 적어 주세요.</p><textarea id="fish-description" class="fish-description" placeholder="예: 몸이 길고 은백색이며 입이 크고 이빨이 날카롭습니다."></textarea><div class="fish-actions"><button class="secondary" id="clear-fish">지우기</button><button class="primary" id="check-fish">위험도 판별</button></div><div class="safe"><span>✓</span> 참고용 안내입니다. 낯선 물고기는 만지지 마세요.</div><div id="fish-result" class="fish-result" hidden></div>`;const input=document.getElementById('fish-description'),result=document.getElementById('fish-result');document.getElementById('clear-fish').onclick=()=>{input.value='';result.hidden=true};document.getElementById('check-fish').onclick=()=>{const t=input.value.trim();if(!t)return show('물고기 특징을 먼저 입력해 주세요.');const h=['독','침','공격','물었','쏘였','전기','복어','상어','해파리'].filter(k=>t.includes(k)),c=['가시','이빨','날카','큰 입','억센','뿔','낯선'].filter(k=>t.includes(k));const level=h.length?'높음':c.length?'주의':'낮음',cls=level==='높음'?'high':level==='주의'?'medium':'low';result.hidden=false;result.className=`fish-result ${cls}`;result.innerHTML=`<b>판정 결과: ${level}</b><p>${level==='높음'?'접촉하지 말고 즉시 거리를 확보하세요. 필요하면 119에 연락하세요.':level==='주의'?'손을 대지 말고 관찰만 하세요.':'뚜렷한 위험 신호가 적지만 야생 물고기는 만지지 마세요.'}</p><small>판별 근거: ${[...h,...c].join(', ')||'입력된 위험 특징 없음'}</small>`}}
